#!/bin/sh

ICON=/usr/share/applications/abuledu-minitexte.desktop
ALACARTEDIR=/usr/share/abuledu-alacarte/data/profile1.applications/

xdg-desktop-menu install  --novendor --mode system ${ICON}

#alacarte
if [ -d "${ALACARTEDIR}" ]; then
    cp ${ICON} ${ALACARTEDIR}
fi

#DEBHELPER#
